project:
  type: website
  output-dir: docs

website:
  title: "SDS 192 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
        - href: projects/scorecard_analysis.qmd
          text: Project 1
        - href: projects/fec-analysis.qmd
          text: Project 2
        - href: projects/mapping.qmd
          text: Project 3

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: source

