project:
  type: website
  output-dir: docs

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  sidebar: 
      - href: projects/scorecard_analysis.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: source

